//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PGTesterApp.AsanPardakhtIPG {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="merchantservicesSoap", Namespace="http://tempuri.org/")]
    public partial class merchantservices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RequestOperationOperationCompleted;
        
        private System.Threading.SendOrPostCallback RequestReconciliationOperationCompleted;
        
        private System.Threading.SendOrPostCallback RequestVerificationOperationCompleted;
        
        private System.Threading.SendOrPostCallback RequestReversalOperationCompleted;
        
        private System.Threading.SendOrPostCallback RequestBatchSettlementOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public merchantservices() {
            this.Url = global::PGTesterApp.Properties.Settings.Default.PGTesterApp_AsanPardakhtIPG_merchantservices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RequestOperationCompletedEventHandler RequestOperationCompleted;
        
        /// <remarks/>
        public event RequestReconciliationCompletedEventHandler RequestReconciliationCompleted;
        
        /// <remarks/>
        public event RequestVerificationCompletedEventHandler RequestVerificationCompleted;
        
        /// <remarks/>
        public event RequestReversalCompletedEventHandler RequestReversalCompleted;
        
        /// <remarks/>
        public event RequestBatchSettlementCompletedEventHandler RequestBatchSettlementCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestOperation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RequestOperation(int merchantConfigurationID, string encryptedRequest) {
            object[] results = this.Invoke("RequestOperation", new object[] {
                        merchantConfigurationID,
                        encryptedRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RequestOperationAsync(int merchantConfigurationID, string encryptedRequest) {
            this.RequestOperationAsync(merchantConfigurationID, encryptedRequest, null);
        }
        
        /// <remarks/>
        public void RequestOperationAsync(int merchantConfigurationID, string encryptedRequest, object userState) {
            if ((this.RequestOperationOperationCompleted == null)) {
                this.RequestOperationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestOperationOperationCompleted);
            }
            this.InvokeAsync("RequestOperation", new object[] {
                        merchantConfigurationID,
                        encryptedRequest}, this.RequestOperationOperationCompleted, userState);
        }
        
        private void OnRequestOperationOperationCompleted(object arg) {
            if ((this.RequestOperationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestOperationCompleted(this, new RequestOperationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestReconciliation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RequestReconciliation(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID) {
            object[] results = this.Invoke("RequestReconciliation", new object[] {
                        merchantConfigurationID,
                        encryptedCredentials,
                        payGateTranID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RequestReconciliationAsync(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID) {
            this.RequestReconciliationAsync(merchantConfigurationID, encryptedCredentials, payGateTranID, null);
        }
        
        /// <remarks/>
        public void RequestReconciliationAsync(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID, object userState) {
            if ((this.RequestReconciliationOperationCompleted == null)) {
                this.RequestReconciliationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestReconciliationOperationCompleted);
            }
            this.InvokeAsync("RequestReconciliation", new object[] {
                        merchantConfigurationID,
                        encryptedCredentials,
                        payGateTranID}, this.RequestReconciliationOperationCompleted, userState);
        }
        
        private void OnRequestReconciliationOperationCompleted(object arg) {
            if ((this.RequestReconciliationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestReconciliationCompleted(this, new RequestReconciliationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestVerification", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RequestVerification(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID) {
            object[] results = this.Invoke("RequestVerification", new object[] {
                        merchantConfigurationID,
                        encryptedCredentials,
                        payGateTranID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RequestVerificationAsync(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID) {
            this.RequestVerificationAsync(merchantConfigurationID, encryptedCredentials, payGateTranID, null);
        }
        
        /// <remarks/>
        public void RequestVerificationAsync(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID, object userState) {
            if ((this.RequestVerificationOperationCompleted == null)) {
                this.RequestVerificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestVerificationOperationCompleted);
            }
            this.InvokeAsync("RequestVerification", new object[] {
                        merchantConfigurationID,
                        encryptedCredentials,
                        payGateTranID}, this.RequestVerificationOperationCompleted, userState);
        }
        
        private void OnRequestVerificationOperationCompleted(object arg) {
            if ((this.RequestVerificationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestVerificationCompleted(this, new RequestVerificationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestReversal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RequestReversal(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID) {
            object[] results = this.Invoke("RequestReversal", new object[] {
                        merchantConfigurationID,
                        encryptedCredentials,
                        payGateTranID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RequestReversalAsync(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID) {
            this.RequestReversalAsync(merchantConfigurationID, encryptedCredentials, payGateTranID, null);
        }
        
        /// <remarks/>
        public void RequestReversalAsync(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID, object userState) {
            if ((this.RequestReversalOperationCompleted == null)) {
                this.RequestReversalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestReversalOperationCompleted);
            }
            this.InvokeAsync("RequestReversal", new object[] {
                        merchantConfigurationID,
                        encryptedCredentials,
                        payGateTranID}, this.RequestReversalOperationCompleted, userState);
        }
        
        private void OnRequestReversalOperationCompleted(object arg) {
            if ((this.RequestReversalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestReversalCompleted(this, new RequestReversalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestBatchSettlement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RequestBatchSettlement(int merchantConfigurationID, string encryptedCredentials) {
            object[] results = this.Invoke("RequestBatchSettlement", new object[] {
                        merchantConfigurationID,
                        encryptedCredentials});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RequestBatchSettlementAsync(int merchantConfigurationID, string encryptedCredentials) {
            this.RequestBatchSettlementAsync(merchantConfigurationID, encryptedCredentials, null);
        }
        
        /// <remarks/>
        public void RequestBatchSettlementAsync(int merchantConfigurationID, string encryptedCredentials, object userState) {
            if ((this.RequestBatchSettlementOperationCompleted == null)) {
                this.RequestBatchSettlementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestBatchSettlementOperationCompleted);
            }
            this.InvokeAsync("RequestBatchSettlement", new object[] {
                        merchantConfigurationID,
                        encryptedCredentials}, this.RequestBatchSettlementOperationCompleted, userState);
        }
        
        private void OnRequestBatchSettlementOperationCompleted(object arg) {
            if ((this.RequestBatchSettlementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestBatchSettlementCompleted(this, new RequestBatchSettlementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RequestOperationCompletedEventHandler(object sender, RequestOperationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestOperationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequestOperationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RequestReconciliationCompletedEventHandler(object sender, RequestReconciliationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestReconciliationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequestReconciliationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RequestVerificationCompletedEventHandler(object sender, RequestVerificationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestVerificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequestVerificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RequestReversalCompletedEventHandler(object sender, RequestReversalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestReversalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequestReversalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RequestBatchSettlementCompletedEventHandler(object sender, RequestBatchSettlementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestBatchSettlementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequestBatchSettlementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591